@extends('layouts.app')
@section('title', 'About TTO')
@section('description', 'Learn about NSU\'s Technology Transfer Office — our mission, vision, services, and team.')

@section('content')

{{-- Hero --}}
<section class="relative hero-clip overflow-hidden" style="min-height: 340px;">
    <div class="absolute inset-0">
        <img src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1400&q=80" alt="" class="w-full h-full object-cover">
        <div class="absolute inset-0" style="background: linear-gradient(135deg, rgba(10,79,81,0.92) 0%, rgba(13,158,160,0.70) 100%);"></div>
    </div>
    <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 text-white">
        <p class="text-tto-amber font-semibold text-sm uppercase tracking-widest mb-3">About</p>
        <h1 class="text-4xl font-bold mb-4">About the Technology Transfer Office</h1>
        <p class="text-white/80 text-lg max-w-2xl">Established to protect, manage, and commercialize intellectual property created by NSU researchers, faculty, and students.</p>
    </div>
</section>

{{-- Mission & Vision --}}
<section class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">
        <div class="fade-up">
            <p class="section-eyebrow">Who We Are</p>
            <h2 class="section-title">Our <span>Mission</span></h2>
            <p class="text-gray-600 leading-relaxed mb-6">
                The Technology Transfer Office (TTO) at North South University is dedicated to facilitating the protection and commercialization of intellectual property generated by university researchers. We serve as the bridge between academic innovation and real-world impact.
            </p>
            <p class="text-gray-600 leading-relaxed mb-6">
                By managing patents, licensing agreements, and startup support, the TTO ensures that NSU's discoveries reach the individuals and industries that can benefit most — creating economic value and societal good for Bangladesh and beyond.
            </p>
            <div class="bg-tto-teal-light border-l-4 border-tto-teal rounded-r-lg p-5">
                <p class="text-tto-teal-dark font-semibold italic leading-relaxed">
                    "To be the premier hub for technology commercialization and innovation in Bangladesh, catalyzing the transformation of university research into sustainable economic and societal impact."
                </p>
                <p class="text-tto-teal text-sm font-medium mt-2">— TTO Vision Statement</p>
            </div>
        </div>
        <div class="fade-up delay-1">
            <p class="section-eyebrow">What We Do</p>
            <h2 class="section-title">Our <span>Objectives</span></h2>
            <div class="space-y-4">
                @php $objectives = [
                    ['icon'=>'M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z', 'title'=>'Protect Intellectual Property', 'desc'=>'Identify, evaluate, and file patents and other IP protections for NSU-created innovations.'],
                    ['icon'=>'M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z', 'title'=>'Build Industry Partnerships', 'desc'=>'Develop strategic relationships with industry partners for sponsored research, licensing, and joint development.'],
                    ['icon'=>'M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z', 'title'=>'Commercialize Research', 'desc'=>'Guide innovations through licensing, technology transfer, and commercialization pathways to market.'],
                    ['icon'=>'M13 10V3L4 14h7v7l9-11h-7z', 'title'=>'Support Startups', 'desc'=>'Provide IP-based startup support including incubation, seed funding connections, and mentorship.'],
                ] @endphp
                @foreach($objectives as $obj)
                <div class="flex gap-4 p-4 bg-white rounded-xl border border-gray-100 card-hover">
                    <div class="w-10 h-10 rounded-lg bg-tto-teal-light flex items-center justify-center flex-shrink-0">
                        <svg class="w-5 h-5 text-tto-teal" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="{{ $obj['icon'] }}"/></svg>
                    </div>
                    <div>
                        <h3 class="font-semibold text-gray-900 mb-1">{{ $obj['title'] }}</h3>
                        <p class="text-sm text-gray-600">{{ $obj['desc'] }}</p>
                    </div>
                </div>
                @endforeach
            </div>
        </div>
    </div>
</section>

{{-- Services --}}
<section class="bg-gray-50 py-20">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-12 fade-up">
            <p class="section-eyebrow justify-center">What We Offer</p>
            <h2 class="section-title">Our <span>Services</span></h2>
            <p class="section-subtitle">End-to-end support for your IP journey</p>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            @php $services = [
                ['title'=>'Invention Disclosure Support', 'desc'=>'Guidance through the disclosure process, from initial concept evaluation to formal submission and ID assignment.', 'icon'=>'M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z'],
                ['title'=>'Patent Filing &amp; Prosecution', 'desc'=>'End-to-end patent filing management including prior art searches, application drafting, and prosecution monitoring.', 'icon'=>'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2'],
                ['title'=>'Licensing &amp; Commercialization', 'desc'=>'Structuring and negotiating technology licensing agreements, MTA, sponsored research, and joint development contracts.', 'icon'=>'M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z'],
                ['title'=>'Startup Incubation', 'desc'=>'IP-based startup support including spin-out formation, seed funding connections, mentorship, and commercialization planning.', 'icon'=>'M13 10V3L4 14h7v7l9-11h-7z'],
                ['title'=>'Revenue Distribution', 'desc'=>'Transparent management of royalty collection and distribution to inventors, departments, and the university according to the approved formula.', 'icon'=>'M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1'],
                ['title'=>'Sponsored Research Support', 'desc'=>'Facilitating agreements between industry partners and NSU researchers, including sponsored research contracts, CDAs, and joint development arrangements.', 'icon'=>'M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z'],
            ] @endphp
            @foreach($services as $svc)
            <div class="bg-white rounded-xl border border-gray-200 p-6 card-hover">
                <div class="w-11 h-11 rounded-xl bg-tto-teal flex items-center justify-center mb-4">
                    <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="{{ $svc['icon'] }}"/></svg>
                </div>
                <h3 class="font-semibold text-gray-900 mb-2">{!! $svc['title'] !!}</h3>
                <p class="text-sm text-gray-600 leading-relaxed">{{ $svc['desc'] }}</p>
            </div>
            @endforeach
        </div>
    </div>
</section>

{{-- Org Chart --}}
<section class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
    <div class="text-center mb-12 fade-up">
        <p class="section-eyebrow justify-center">Governance</p>
        <h2 class="section-title">Organizational <span>Structure</span></h2>
        <p class="section-subtitle">Governance and management of the Technology Transfer Office</p>
    </div>
    <div class="flex flex-col items-center">
        <div class="org-node bg-tto-teal text-white border-tto-teal font-semibold px-8 py-3 fade-up">Director, TTO</div>

        {{-- Desktop: proper T-junction connector --}}
        <div class="hidden lg:block w-full max-w-3xl">
            <div class="flex justify-center">
                <div class="w-px h-5" style="background:#0D9EA0;opacity:.5;"></div>
            </div>
            <div class="relative">
                {{-- Horizontal bar spanning center-of-col-1 to center-of-col-4 --}}
                <div class="absolute top-0 h-px" style="background:#0D9EA0;opacity:.4;left:calc(12.5% - 6px);right:calc(12.5% - 6px);"></div>
                <div class="grid grid-cols-4 gap-4">
                    @foreach(['TTO Officer', 'Legal Officer', 'Reviewer', 'System Administrator'] as $role)
                    <div class="flex flex-col items-center">
                        <div class="w-px h-5" style="background:#0D9EA0;opacity:.5;"></div>
                        <div class="org-node w-full">{{ $role }}</div>
                    </div>
                    @endforeach
                </div>
            </div>
        </div>

        {{-- Mobile: simple grid, no connectors --}}
        <div class="lg:hidden w-full max-w-xl mt-4 grid grid-cols-2 gap-4">
            @foreach(['TTO Officer', 'Legal Officer', 'Reviewer', 'System Administrator'] as $role)
            <div class="org-node">{{ $role }}</div>
            @endforeach
        </div>
    </div>
</section>

{{-- Team --}}
<section class="bg-tto-teal-light py-20">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-12 fade-up">
            <p class="section-eyebrow justify-center">Our People</p>
            <h2 class="section-title">Meet the <span>Team</span></h2>
            <p class="section-subtitle">The dedicated professionals behind NSU's technology transfer activities</p>
        </div>
        <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-6 mb-8">
            @foreach(['Director', 'TTO Officer', 'Legal Officer', 'Reviewer', 'System Administrator'] as $role)
            <div class="bg-white rounded-xl border border-gray-200 p-5 text-center opacity-50">
                <div class="w-14 h-14 rounded-full bg-gray-100 border-2 border-dashed border-gray-300 flex items-center justify-center mx-auto mb-4">
                    <svg class="w-6 h-6 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/></svg>
                </div>
                <div class="h-3 bg-gray-200 rounded-full w-3/4 mx-auto mb-2"></div>
                <div class="h-2.5 bg-gray-100 rounded-full w-1/2 mx-auto mb-1"></div>
                <p class="text-xs text-gray-400 mt-2">{{ $role }}</p>
            </div>
            @endforeach
        </div>
        <p class="text-center text-sm text-gray-400 fade-up">Staff bios and photos will be added by the TTO administrator. <a href="{{ route('contact') }}" class="text-tto-teal hover:underline">Get in touch</a> in the meantime.</p>
    </div>
</section>

@endsection
